[colors.bright]
black = "0x0F4039"
blue = "0xCCFFCC"
cyan = "0xCCEEFF"
green = "0x44BB55"
magenta = "0xAA88AA"
red = "0xFF5555"
white = "0xFFEEEE"
yellow = "0xFFEEAA"

[colors.cursor]
cursor = "0xAA4444"
text = "0xFEFFCC"

[colors.dim]
black = "0x232323"
blue = "0x556b79"
cyan = "0x5c8482"
green = "0x5e6547"
magenta = "0x6e4962"
red = "0x74423f"
white = "0x828282"
yellow = "0x8b7653"

[colors.normal]
black = "0x020A04"
blue = "0x4040FF"
cyan = "0x0FD0D9"
green = "0x11EE77"
magenta = "0xCC66CC"
red = "0xFc5F5F"
white = "0xFFCCCC"
yellow = "0xAA7733"

[colors.primary]
background = "0x222233"
#bright_background = "0x3a3a3a"
bright_foreground = "0xFFd9d9"
#dim_background = "0x202020"
dim_foreground = "0xdbdbdb"
foreground = "0xFEFFCC"

[font]
size = 10.0

[font.bold]
family = "Fira Code"
style = "ExtraBold"

[font.italic]
family = "Fira Code"

[font.normal]
family = "Fira Code"
style = "Regular"
